test:
  single:
    enabledVariants:
      - Horizontal (Compact)
      - Horizontal (Stream D)
      - Horizontal (Stream R)
      - Spring Data JDBC (Single Query)
  list:
    enabledVariants:
      - Horizontal (Compact)
      - Horizontal (Stream D)
      - Horizontal (Stream R)
      - Spring Data JDBC (Single Query)

